[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
elpis-protocol = { path = "../crates/elpis-protocol" }
elpis-runtime = { path = "../crates/elpis-runtime" }
flate2.workspace = true
fs2.workspace = true
hex.workspace = true
libc.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true
ureq.workspace = true

[dev-dependencies]
tempfile = "3"
