import { test } from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  applyReleaseSync,
  planReleaseSync,
  ReleaseSyncError,
  runReleaseSyncCli,
  verifyReleaseSync,
  type ReleaseSyncDependencies,
} from '../src/release-sync.js';
import type { ReleaseCommit } from '../src/release-version.js';

const commits: ReleaseCommit[] = [{ sha: 'abcdef1', subject: 'fix: repair' }];

const canonical = (value: unknown): string =>
  `${JSON.stringify(value, null, 2)}\n`;

const fixture = async (): Promise<string> => {
  const root = await fs.mkdtemp(
    path.join(tmpdir(), 'elpis-release-sync-test-'),
  );
  await fs.mkdir(path.join(root, 'rust/crates/elpis-a/src'), {
    recursive: true,
  });
  await fs.writeFile(path.join(root, 'VERSION'), '0.1.0\n');
  await fs.writeFile(
    path.join(root, 'package.json'),
    canonical({ name: 'elpis', version: '0.1.0', private: true }),
  );
  await fs.writeFile(
    path.join(root, 'package-lock.json'),
    canonical({
      name: 'elpis',
      version: '0.1.0',
      lockfileVersion: 3,
      requires: true,
      packages: { '': { name: 'elpis', version: '0.1.0' } },
    }),
  );
  await fs.writeFile(
    path.join(root, 'rust/Cargo.toml'),
    '[workspace]\nmembers = [\n  "crates/elpis-a",\n]\nresolver = "3"\n\n[workspace.package]\nversion = "0.1.0"\nedition = "2024"\n',
  );
  await fs.writeFile(
    path.join(root, 'rust/crates/elpis-a/Cargo.toml'),
    '[package]\nname = "elpis-a"\nversion.workspace = true\nedition.workspace = true\n',
  );
  await fs.writeFile(path.join(root, 'rust/crates/elpis-a/src/lib.rs'), '');
  await fs.writeFile(
    path.join(root, 'rust/Cargo.lock'),
    '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "elpis-a"\nversion = "0.1.0"\n',
  );
  return root;
};

const snapshot = async (root: string): Promise<Map<string, Buffer>> => {
  const result = new Map<string, Buffer>();
  for (const relative of [
    'VERSION',
    'package.json',
    'package-lock.json',
    'rust/Cargo.toml',
    'rust/Cargo.lock',
  ]) {
    result.set(relative, await fs.readFile(path.join(root, relative)));
  }
  return result;
};

const unchanged = async (
  root: string,
  before: Map<string, Buffer>,
): Promise<void> => {
  for (const [relative, bytes] of before) {
    assert.deepEqual(
      await fs.readFile(path.join(root, relative)),
      bytes,
      relative,
    );
  }
};

const stubCargo: ReleaseSyncDependencies['verifyCargoLock'] = async (
  _root,
  cargoToml,
  cargoLock,
) => {
  assert.match(cargoToml.toString('utf8'), /version = "0\.1\.1"/);
  assert.match(cargoLock.toString('utf8'), /version = "0\.1\.1"/);
};

test('verify and plan read all canonical version sources without mutation', async (t) => {
  const root = await fixture();
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const before = await snapshot(root);
  const verified = await verifyReleaseSync(root, '0.1.0');
  assert.equal(verified.mode, 'verify');
  assert.equal(
    verified.versionState['Cargo-lock-workspace'][0].name,
    'elpis-a',
  );
  const planned = await planReleaseSync(root, 'v0.1.0', commits);
  assert.equal(planned.nextVersion, '0.1.1');
  assert.deepEqual(planned.changedPaths, [
    'VERSION',
    'package.json',
    'package-lock.json',
    'rust/Cargo.toml',
    'rust/Cargo.lock',
  ]);
  await unchanged(root, before);
});

test('validation mismatch fails before any repository file changes', async (t) => {
  const root = await fixture();
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const lockPath = path.join(root, 'package-lock.json');
  const lock = JSON.parse(await fs.readFile(lockPath, 'utf8')) as Record<
    string,
    unknown
  >;
  lock.version = '0.1.1';
  await fs.writeFile(lockPath, canonical(lock));
  const before = await snapshot(root);
  await assert.rejects(
    applyReleaseSync(root, 'v0.1.0', commits, { verifyCargoLock: stubCargo }),
  );
  await unchanged(root, before);
});

test('apply changes exactly five version files after candidate verification', async (t) => {
  const root = await fixture();
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const beforeModes = new Map<string, number>();
  for (const relative of [
    'VERSION',
    'package.json',
    'package-lock.json',
    'rust/Cargo.toml',
    'rust/Cargo.lock',
  ]) {
    beforeModes.set(
      relative,
      (await fs.stat(path.join(root, relative))).mode & 0o777,
    );
  }
  const receipt = await applyReleaseSync(root, 'v0.1.0', commits, {
    verifyCargoLock: stubCargo,
  });
  assert.equal(receipt.mode, 'apply');
  assert.equal(receipt.nextVersion, '0.1.1');
  assert.equal((await verifyReleaseSync(root, '0.1.1')).nextVersion, '0.1.1');
  assert.equal(
    JSON.parse(await fs.readFile(path.join(root, 'package.json'), 'utf8'))
      .version,
    '0.1.1',
  );
  const lock = JSON.parse(
    await fs.readFile(path.join(root, 'package-lock.json'), 'utf8'),
  );
  assert.equal(lock.version, '0.1.1');
  assert.equal(lock.packages[''].version, '0.1.1');
  const beforeRepeat = await snapshot(root);
  await assert.rejects(
    applyReleaseSync(root, 'v0.1.0', commits, { verifyCargoLock: stubCargo }),
  );
  await unchanged(root, beforeRepeat);
  for (const [relative, mode] of beforeModes) {
    assert.equal((await fs.stat(path.join(root, relative))).mode & 0o777, mode);
  }
  assert.deepEqual(
    (await fs.readdir(root)).filter((name) =>
      name.startsWith('.release-sync-'),
    ),
    [],
  );
  assert.deepEqual(
    (await fs.readdir(path.join(root, 'rust'))).filter((name) =>
      name.startsWith('.release-sync-'),
    ),
    [],
  );
});

test('Cargo candidate verification failure leaves every repository file unchanged', async (t) => {
  const root = await fixture();
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const before = await snapshot(root);
  await assert.rejects(
    applyReleaseSync(root, 'v0.1.0', commits, {
      verifyCargoLock: async () => {
        throw new ReleaseSyncError('injected Cargo verification failure');
      },
    }),
    /injected Cargo verification failure/,
  );
  await unchanged(root, before);
});

test('rename failure rolls back every already-replaced file', async (t) => {
  const root = await fixture();
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const before = await snapshot(root);
  let calls = 0;
  const rename: NonNullable<ReleaseSyncDependencies['rename']> = async (
    from,
    to,
  ) => {
    calls += 1;
    if (calls === 3) throw new Error('injected rename failure');
    await fs.rename(from, to);
  };
  await assert.rejects(
    applyReleaseSync(root, 'v0.1.0', commits, {
      verifyCargoLock: stubCargo,
      rename,
    }),
    ReleaseSyncError,
  );
  await unchanged(root, before);
});

test('CLI emits one bounded JSON line and rejects duplicate arguments', async (t) => {
  const root = await fixture();
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  let output = '';
  await runReleaseSyncCli(
    ['verify', '--root', root, '--version', '0.1.0'],
    (text) => (output += text),
  );
  assert.equal(output.split('\n').length, 2);
  assert.equal(JSON.parse(output).format, 'elpis-release-sync-v1');
  const commitFile = path.join(root, 'commits.json');
  await fs.writeFile(commitFile, canonical(commits));
  output = '';
  await runReleaseSyncCli(
    ['plan', '--root', root, '--tag', 'v0.1.0', '--commits', commitFile],
    (text) => (output += text),
  );
  assert.equal(JSON.parse(output).nextVersion, '0.1.1');
  await assert.rejects(
    runReleaseSyncCli([
      'verify',
      '--root',
      root,
      '--root',
      root,
      '--version',
      '0.1.0',
    ]),
    ReleaseSyncError,
  );
});
