[package]
name = "elpis-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
elpis-protocol = { path = "../elpis-protocol" }
thiserror.workspace = true

[dev-dependencies]
elpis-journal = { path = "../elpis-journal" }
elpis-transport = { path = "../elpis-transport" }
serde_json.workspace = true
tempfile = "3"
