export {
  CANONICAL_CREDENTIALS,
  CREDENTIAL_VECTORS,
  createEnrollmentCredential,
  createNodeCredential,
  exactVerifier,
  isCredentialId,
  isGatewayInstanceId,
  newGatewayInstanceId,
  parseEnrollmentCredential,
  parseNodeCredential,
  verifierMatches,
  type GatewayCredentialMaterial,
  type GatewayCredentialVector,
  type ParsedGatewayCredential,
  type RandomBytes,
} from '@elpis/gateway-protocol';
